### PR TITLE
Simplify/refactor the Wagtail Markdown Editor

### PR DESCRIPTION
**Pull request by marcofucci**
As @tomdyson suggested, this way of adding a markdown editor is cleaner and more flexible.

### CODE REVIEW

**Comment by marcofucci** [comment]
This could actually be a separate package.

**Comment by tomdyson** [comment]
This looks solid, @marcofucci! 

> This could actually be a separate package.

Yes! There are currently ~5 wagtail-markdown packages floating around, but I'm keen to get one in core, and your implementation looks the most complete so far. The missing part is integrating images / docs / embeds / internal links, but we could add that later. Do you have time to submit a PR to Wagtail, based on your work here?

**Comment by marcofucci** [comment]
@tomdyson I've spent a bit of time on it and I don't see any clean way of doing this by keeping the same richtext logic.

The problem is that the the current richtext component is expecting html as value in the db whilst markdown wants raw md instead.

This means that using a different `SimpleMDETextArea` widget in the admin works fine but the rendering logic is too tight to the `RichText` class, the `richtext` filter and related functions (e.g. `expand_db_html`) which deal with html values.

Therefore, treating markdown components as an extension of richtext might not be the best option and maybe the previous version (separate block/field etc.) was superior.

This repo doesn't really care too much about the templating bit as wagtail is used as a Headless Content Store so that's why the problem is not immediately obvious here.

**Comment by tomdyson** [comment]
Thanks for explaining this, @marcofucci, and sorry if I took you down a blind alley.

FYI there's a separate effort to re-model both the standard RTE implementation and the internal representation of RT content:

- https://github.com/springload/draftjs_exporter
- https://springload.github.io/draftail/

I imagine you'll need to support internal links / images / docs eventually, which may require extensions to the Markdown syntax, in a similar way to Github's issue and username references:

https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Pull request merged**
